
const STATE={data:null,active:new Set(),query:"",type:"all",favorites:new Set(JSON.parse(localStorage.getItem("favorites")||"[]")),view:"dashboard"};
const MONTHS=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const WD=["D","S","T","Q","Q","S","S"];
const semStart=new Date("2026-08-03T00:00:00"),semEnd=new Date("2026-12-04T23:59:59");
const $=s=>document.querySelector(s);
function d(s){return new Date(s+"T12:00:00")}
function fmt(s){const x=d(s);return String(x.getDate()).padStart(2,"0")+"/"+String(x.getMonth()+1).padStart(2,"0")}
function classify(e){const t=(e.label+" "+(e.time||"")).toLowerCase();if(/a confirmar|base 2025|data provável/.test(t))return"pending";if(/prova|av1|av2|av3|av4|av6|modular|exame especial|atividade integradora|avaliativo|avaliação parcial|avaliação final/.test(t))return"assessment";if(/ambulatório|ambulatorial|triagem|consulta/.test(t))return"ambulatory";if(/\bgd\b|gd\d/.test(t))return"gd";return"class"}
function disc(k){return STATE.data.disciplines[k]}
function visible(e){if(!STATE.active.has(e.disc))return false;if(STATE.type!=="all"&&e.type!==STATE.type)return false;const h=(disc(e.disc).name+" "+e.label+" "+(e.time||"")).toLowerCase();return!STATE.query||h.includes(STATE.query)}
function end(e){return e.end?d(e.end):d(e.date)}
function daysOf(e){const a=[];let x=d(e.date),z=end(e);while(x<=z){a.push(x.toISOString().slice(0,10));x=new Date(x.getTime()+86400000)}return a}
function eid(e){return `${e.disc}|${e.date}|${e.label}`}
function saveFav(){localStorage.setItem("favorites",JSON.stringify([...STATE.favorites]))}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function app(){return `<div class="shell"><div class="top">
<section class="hero"><div><div class="eyebrow">Medicina UFMG · Ciclo Clínico · 6º Período</div><h1>Calendário Premium — Turma A</h1><div class="sub">2º semestre de 2026 · avaliações, GDs, aulas, ambulatórios e integradoras</div></div><div id="countdown" class="countdown"></div></section>
<div class="controls"><input id="search" class="ctrl search" placeholder="Buscar prova, GD, tema ou disciplina…"><select id="type" class="ctrl"><option value="all">Todos os tipos</option><option value="assessment">Provas e avaliações</option><option value="gd">GDs</option><option value="ambulatory">Ambulatórios/consultas</option><option value="class">Aulas/ATs</option><option value="pending">A confirmar</option></select><button id="theme" class="ctrl btn">🌙 Tema</button><button id="icsAll" class="ctrl btn">📅 ICS completo</button><button id="icsDisc" class="ctrl btn primary">🎨 ICS por matéria</button></div>
<div class="nav">${[["dashboard","Dashboard"],["calendar","Calendário"],["timeline","Agenda"],["disciplines","Disciplinas"],["favorites","Favoritos"],["settings","Configurações"]].map(([k,v])=>`<button data-view="${k}" class="${k==="dashboard"?"active":""}">${v}</button>`).join("")}</div></div>
<main><section id="dashboard" class="view active"></section><section id="calendar" class="view"></section><section id="timeline" class="view"></section><section id="disciplines" class="view"></section><section id="favorites" class="view"></section><section id="settings" class="view"></section></main><div class="footer">Calendário acadêmico pessoal · versão final 2026/2</div></div><div id="toast" class="toast"></div>`}
function render(){renderCountdown();renderDashboard();renderCalendar();renderTimeline();renderDisciplines();renderFavorites();renderSettings();bind()}
function renderCountdown(){const now=new Date();now.setHours(0,0,0,0);const l=STATE.data.events.filter(visible).filter(e=>end(e)>=now).sort((a,b)=>d(a.date)-d(b.date));const b=$("#countdown");if(!l.length){b.innerHTML="<div><div class='cd-title'>Sem eventos futuros 🎉</div></div>";return}const e=l[0],diff=Math.max(0,Math.ceil((d(e.date)-now)/86400000));b.innerHTML=`<div><div class="cd-number">${diff===0?"HOJE":diff}</div><div class="cd-label">${diff===0?"em andamento":diff===1?"dia faltando":"dias faltando"}</div></div><div><div class="cd-title">${disc(e.disc).icon} ${disc(e.disc).name} — ${e.label}</div><div class="cd-meta">${fmt(e.date)}${e.time?" · "+e.time:""}</div></div>`}
function legend(){return `<div class="legend">${Object.entries(STATE.data.disciplines).map(([k,v])=>`<button data-disc="${k}" class="${STATE.active.has(k)?"":"off"}"><span class="dot" style="background:${v.color}"></span>${v.name}</button>`).join("")}</div>`}
function timelineRows(list){if(!list.length)return"<div class='empty'>Nenhum evento.</div>";return `<div class="timeline">${list.map(e=>`<div class="trow"><div class="tdate">${fmt(e.date)}</div><div class="tdot" style="background:${disc(e.disc).color}"></div><div class="tcard"><button class="favorite ${STATE.favorites.has(eid(e))?"on":""}" data-fav="${encodeURIComponent(eid(e))}">${STATE.favorites.has(eid(e))?"⭐":"☆"}</button><b>${disc(e.disc).icon} ${disc(e.disc).name} — ${e.label}</b><small>${e.time||""}${e.end?" · até "+fmt(e.end):""}</small></div></div>`).join("")}</div>`}
function renderDashboard(){const ev=STATE.data.events.filter(visible),a=ev.filter(e=>e.type==="assessment").length,g=ev.filter(e=>e.type==="gd").length,m=ev.filter(e=>e.type==="ambulatory").length,p=ev.filter(e=>e.type==="pending").length;const now=new Date(),pct=Math.round(Math.min(1,Math.max(0,(now-semStart)/(semEnd-semStart)))*100),future=ev.filter(e=>end(e)>=now).sort((x,y)=>d(x.date)-d(y.date)).slice(0,10);$("#dashboard").innerHTML=`<div class="stats">${[["Eventos",ev.length],["Avaliações",a],["GDs",g],["Ambulatórios",m],["A confirmar",p],["Favoritos",STATE.favorites.size]].map(([k,v])=>`<div class="card"><div class="metric">${v}</div><div class="label">${k}</div></div>`).join("")}</div><div class="card progress"><div class="progress-head"><b>Progresso do semestre</b><span>${pct}%</span></div><div class="track"><div class="fill" style="width:${pct}%"></div></div></div>${legend()}<div class="grid2"><div class="panel"><h2>Próximos eventos</h2>${timelineRows(future)}</div><div class="panel"><h2>Próximas avaliações</h2><div class="quick-list">${ev.filter(e=>e.type==="assessment"&&end(e)>=now).sort((x,y)=>d(x.date)-d(y.date)).slice(0,8).map(e=>`<div class="quick-item" style="--c:${disc(e.disc).color}"><b>${fmt(e.date)} · ${disc(e.disc).name}</b><small>${e.label}${e.time?" · "+e.time:""}</small></div>`).join("")||"<div class='empty'>Nenhuma avaliação futura.</div>"}</div></div></div>`}
function renderCalendar(){const cards=[7,8,9,10,11].map(m=>{const first=new Date(2026,m,1),count=new Date(2026,m+1,0).getDate();let cells="<div></div>".repeat(first.getDay());for(let n=1;n<=count;n++){const iso=`2026-${String(m+1).padStart(2,"0")}-${String(n).padStart(2,"0")}`,es=STATE.data.events.filter(visible).filter(e=>daysOf(e).includes(iso)),today=new Date();cells+=`<div class="day ${es.some(e=>e.end)?"range":""} ${today.getFullYear()===2026&&today.getMonth()===m&&today.getDate()===n?"today":""}" title="${es.map(e=>disc(e.disc).name+" — "+e.label).join("\n")}"><div class="num">${n}</div><div class="marks">${[...new Set(es.map(e=>e.disc))].map(k=>`<span class="mark" style="background:${disc(k).color}"></span>`).join("")}</div></div>`}const list=STATE.data.events.filter(visible).filter(e=>d(e.date).getMonth()===m).sort((a,b)=>d(a.date)-d(b.date));return `<div class="month"><div class="mhead"><span>${MONTHS[m].toUpperCase()}</span><span>2026</span></div><div class="week">${WD.map(x=>`<div>${x}</div>`).join("")}</div><div class="days">${cells}</div><div class="mlist">${list.length?list.map(e=>`<div class="mrow"><span class="chip" style="background:${disc(e.disc).color}">${fmt(e.date)}</span><div><b>${disc(e.disc).name}</b><br><small>${e.label}${e.time?" · "+e.time:""}</small></div></div>`).join(""):"<div class='empty'>Sem eventos.</div>"}</div></div>`}).join("");$("#calendar").innerHTML=`${legend()}<div class="calendar-grid">${cards}</div>`}
function renderTimeline(){const l=STATE.data.events.filter(visible).sort((a,b)=>d(a.date)-d(b.date));$("#timeline").innerHTML=`<div class="panel"><h2>Agenda cronológica</h2>${timelineRows(l)}</div>`}
function renderDisciplines(){$("#disciplines").innerHTML=`<div class="disc-grid">${Object.entries(STATE.data.disciplines).map(([k,v])=>{const l=STATE.data.events.filter(e=>e.disc===k&&visible(e));return `<div class="disc-card" style="border-top:6px solid ${v.color}"><h3>${v.icon} ${v.name}</h3><div class="disc-count">${l.length}</div><div class="mini">eventos visíveis</div>${l.slice(0,7).map(e=>`<div class="mini">• ${fmt(e.date)} — ${e.label}</div>`).join("")}</div>`}).join("")}</div>`}
function renderFavorites(){const l=STATE.data.events.filter(e=>STATE.favorites.has(eid(e))).sort((a,b)=>d(a.date)-d(b.date));$("#favorites").innerHTML=`<div class="panel"><h2>Favoritos</h2>${timelineRows(l)}</div>`}
function renderSettings(){$("#settings").innerHTML=`<div class="panel"><h2>Configurações</h2><div class="settings-grid"><div class="setting"><b>Tema</b><p class="label">Claro ou escuro. A escolha fica salva.</p></div><div class="setting"><b>Lembretes ICS</b><p class="label">5 dias antes e 1 dia antes.</p></div><div class="setting"><b>Cores no iPhone</b><p class="label">Use “ICS por matéria” e importe cada matéria em um calendário separado.</p></div><div class="setting"><b>Adicionar à Tela de Início</b><p class="label">No Safari do iPhone: Compartilhar → Adicionar à Tela de Início.</p></div></div></div>`}
function bind(){$("#search").value=STATE.query;$("#type").value=STATE.type;$("#search").oninput=e=>{STATE.query=e.target.value.trim().toLowerCase();render()};$("#type").onchange=e=>{STATE.type=e.target.value;render()};$("#theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light")};document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{STATE.view=b.dataset.view;document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===STATE.view))});document.querySelectorAll("[data-disc]").forEach(b=>b.onclick=()=>{STATE.active.has(b.dataset.disc)?STATE.active.delete(b.dataset.disc):STATE.active.add(b.dataset.disc);render()});document.querySelectorAll("[data-fav]").forEach(b=>b.onclick=()=>{const id=decodeURIComponent(b.dataset.fav);STATE.favorites.has(id)?STATE.favorites.delete(id):STATE.favorites.add(id);saveFav();render();toast("Favoritos atualizados")});$("#icsAll").onclick=()=>download("Calendario_Turma_A_Completo.ics",icsFor(STATE.data.events.filter(visible),"Turma A — 2026/2","#111827"));$("#icsDisc").onclick=()=>{Object.entries(STATE.data.disciplines).forEach(([k,v],i)=>setTimeout(()=>download(v.name.replaceAll(" ","_")+".ics",icsFor(STATE.data.events.filter(e=>e.disc===k&&visible(e)),v.name,v.color)),i*350))}}
function esc(s){return(s||"").replaceAll("\\","\\\\").replaceAll("\n","\\n").replaceAll(",","\\,").replaceAll(";","\\;")}
function times(s){return[...((s||"").matchAll(/(\d{1,2})h(\d{2})?/g))].map(m=>[+m[1],+(m[2]||0)])}
function icsFor(list,name,c){const stamp=new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z/,"Z");let o=["BEGIN:VCALENDAR","VERSION:2.0","CALSCALE:GREGORIAN",`X-WR-CALNAME:${esc(name)}`,`X-APPLE-CALENDAR-COLOR:${c}`];list.forEach((e,i)=>{const ds=e.date.replaceAll("-",""),t=e.end?[]:times(e.time);o.push("BEGIN:VEVENT",`UID:${e.disc}-${ds}-${i}@turmaa`,`DTSTAMP:${stamp}`);if(t.length){const [sh,sm]=t[0],[eh,em]=t[1]||[Math.min(sh+1,23),sm];o.push(`DTSTART;TZID=America/Sao_Paulo:${ds}T${String(sh).padStart(2,"0")}${String(sm).padStart(2,"0")}00`,`DTEND;TZID=America/Sao_Paulo:${ds}T${String(eh).padStart(2,"0")}${String(em).padStart(2,"0")}00`)}else{const z=new Date((e.end||e.date)+"T00:00:00");z.setDate(z.getDate()+1);o.push(`DTSTART;VALUE=DATE:${ds}`,`DTEND;VALUE=DATE:${z.toISOString().slice(0,10).replaceAll("-","")}`)}o.push(`SUMMARY:${esc(e.label)}`,`DESCRIPTION:${esc(disc(e.disc).name+" — "+e.label+(e.time?" ("+e.time+")":""))}`,"BEGIN:VALARM","ACTION:DISPLAY","TRIGGER:-P5D","DESCRIPTION:Faltam 5 dias","END:VALARM","BEGIN:VALARM","ACTION:DISPLAY","TRIGGER:-P1D","DESCRIPTION:Falta 1 dia","END:VALARM","END:VEVENT")});o.push("END:VCALENDAR");return o.join("\r\n")}
function download(n,t){const b=new Blob([t],{type:"text/calendar;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}
document.addEventListener("DOMContentLoaded",()=>{document.body.innerHTML=app();if(localStorage.getItem("theme")==="dark")document.body.classList.add("dark");fetch("./eventos.json").then(r=>r.json()).then(x=>{STATE.data=x;STATE.data.events.forEach(e=>e.type=classify(e));Object.keys(x.disciplines).forEach(k=>STATE.active.add(k));render()}).catch(()=>document.body.innerHTML="<div class='loading'>Não foi possível carregar eventos.json.</div>");if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})})
